#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided. 
#
# Note: Content strings here are truncated for example purposes.
# Run yum upgrade
package_upgrade: true

# Create custom condor configuration file to create an execute node
write_files:
-   content: |
        ##  What machine is your central manager?
        
        CONDOR_HOST = 158.39.77.41, 158.39.77.187
        
        ## Pool's short description
        
        COLLECTOR_NAME = Personal Condor at $(FULL_HOSTNAME)
        
        ##  When is this machine willing to start a job?
        
        START = TRUE
        
        
        ##  When to suspend a job?
        
        SUSPEND = FALSE
        
        
        ##  When to nicely stop a job?
        ##  (as opposed to killing it instantaneously)
        
        PREEMPT = FALSE
        
        
        ##  When to instantaneously kill a preempting job
        ##  (e.g. if a job is in the pre-empting stage for too long)
        
        KILL = FALSE
        
        
        ##  This macro determines what daemons the condor_master will start and keep its watchful eyes on.
        ##  The list is a comma or space separated list of subsystem names
        
        DAEMON_LIST = MASTER, STARTD
        DISCARD_SESSION_KEYRING_ON_STARTUP = False
        
        UID_DOMAIN = uib.no
        DEFAULT_DOMAIN_NAME = uib.no
        TRUST_UID_DOMAIN = TRUE
        SOFT_UID_DOMAIN=true
        
        NUM_SLOTS = 1
        NUM_SLOTS_TYPE_1 = 1
        SLOT_TYPE_1 = cpus=100%
        SLOT_TYPE_1_PARTITIONABLE = true
    owner: root:root
    path: /etc/condor/config.d/00personal_condor.config
    permissions: '0644'
runcmd:
- condor_reconfig

