#cloud-config
# vim: syntax=yaml
#
# This is the configuration syntax that the write_files module
# will know how to understand. encoding can be given b64 or gzip or (gz+b64).
# The content will be decoded accordingly and then written to the path that is
# provided. 
#
# Note: Content strings here are truncated for example purposes.
# Run yum upgrade
package_upgrade: true

# Create custom condor configuration file to create an execute node
write_files:
-   content: |
        ##  What machine is your central manager?
        
        CONDOR_HOST = your.host.machine.ip
        
        ##  This macro determines what daemons the condor_master will start and keep its watchful eyes on.
        ##  The list is a comma or space separated list of subsystem names
        
        DAEMON_LIST = COLLECTOR, MASTER, NEGOTIATOR
        
        FLOCK_TO = $(CONDOR_HOST)
        ALLOW_NEGOTIATOR = $(FLOCK_TO)
        ALLOW_WRITE = execute.node.ip.*
        ALLOW_READ = $(ALLOW_WRITE)
        UID_DOMAIN = a.name.that.does.not.have.to.resolve.to.some.web.address.to.work
        STARTER_ALLOW_RUNAS_OWNER = TRUE
        TRUST_UID_DOMAIN=TRUE
        SOFT_UID_DOMAIN = TRUE
        
        NEGOTIATOR_INTERVAL = 5
    owner: root:root
    path: /etc/condor/config.d/00personal_condor.config
    permissions: '0644'
runcmd:
- condor_reconfig

